# .github/workflows/release.yml
# Builds and creates GitHub Release with APKs

name: Build and Release

'on':
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

# Grant permissions to create releases
permissions:
  contents: write

jobs:
  build-and-release:
    name: Build APKs and Create Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'

      # Step 4: Get dependencies
      - name: Install dependencies
        run: flutter pub get


      # Step 6: Build all three flavors
      - name: Build Dev APK
        run: flutter build apk -t lib/main_dev.dart --flavor dev

      - name: Build Staging APK
        run: flutter build apk -t lib/main_staging.dart --flavor staging

      - name: Build Production APK
        run: flutter build apk -t lib/main_prod.dart --flavor prod

      # Step 7: Rename APKs for clarity
      - name: Rename APKs
        run: |
          mkdir -p release_apks
          cp build/app/outputs/flutter-apk/app-dev-release.apk release_apks/MyApp-dev-${{ github.ref_name }}.apk
          cp build/app/outputs/flutter-apk/app-staging-release.apk release_apks/MyApp-staging-${{ github.ref_name }}.apk
          cp build/app/outputs/flutter-apk/app-prod-release.apk release_apks/MyApp-prod-${{ github.ref_name }}.apk

      # Step 8: Create GitHub Release with all APKs
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_apks/MyApp-dev-${{ github.ref_name }}.apk
            release_apks/MyApp-staging-${{ github.ref_name }}.apk
            release_apks/MyApp-prod-${{ github.ref_name }}.apk
          body: |
            ## 📱 Download and Install
            
            Choose the appropriate version for your needs:
            
            ### 🟢 Development Build
            - For developers and early testing
            - Points to dev API server
            - Debug logging enabled
            
            ### 🟠 Staging Build
            - For QA and internal testing
            - Points to staging API server
            - Pre-production testing
            
            ### 🔵 Production Build
            - For end users
            - Points to production API server
            - Optimized and stable
            
            ---
            
            ### Installation Instructions
            
            1. Download the APK file for your environment
            2. Transfer to your Android device (if downloaded on computer)
            3. On your device, go to **Settings** → **Security**
            4. Enable **"Install from Unknown Sources"** or **"Allow from this source"**
            5. Open the APK file and tap **Install**
            
            ---
            
            **Version**: ${{ github.ref_name }}
            **Build Date**: ${{ github.event.head_commit.timestamp }}
            **Commit**: ${{ github.sha }}
            
            ### Changes in this release
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}